CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cpf TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ADMIN', 'USER')),
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS service_order_locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS occurrence_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS service_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  location_text TEXT,
  expected_start TIMESTAMPTZ NOT NULL,
  expected_duration_hours INTEGER NOT NULL CHECK (expected_duration_hours > 0),
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED')),
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  closed_by INTEGER REFERENCES users(id)
);

ALTER TABLE service_orders
  ADD COLUMN IF NOT EXISTS location_id INTEGER REFERENCES service_order_locations(id),
  ADD COLUMN IF NOT EXISTS occurrence_type_id INTEGER REFERENCES occurrence_types(id),
  ADD COLUMN IF NOT EXISTS replaced_user_id INTEGER REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS cover_user_id INTEGER REFERENCES users(id);

CREATE TABLE IF NOT EXISTS service_order_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_order_id INTEGER NOT NULL REFERENCES service_orders(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(service_order_id, user_id)
);

CREATE TABLE IF NOT EXISTS times_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('IN', 'OUT')),
  occurred_at TIMESTAMPTZ NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  location_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  note TEXT,
  adjusted_by INTEGER REFERENCES users(id),
  adjusted_at TIMESTAMPTZ,
  adjustment_note TEXT,
  source_alert_id INTEGER,
  service_order_id INTEGER REFERENCES service_orders(id)
);

CREATE TABLE IF NOT EXISTS alerts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_in_entry_id INTEGER REFERENCES times_entries(id) ON DELETE SET NULL,
  severity INTEGER NOT NULL DEFAULT 1,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  resolved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  resolution_note TEXT
);

CREATE TABLE IF NOT EXISTS missed_punch_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  requested_type TEXT CHECK (requested_type IN ('IN', 'OUT')),
  requested_occurred_at TIMESTAMPTZ,
  note TEXT,
  signature_data_url TEXT,
  employee_name TEXT,
  forgotten_date DATE,
  entry_time TIME,
  exit_time TIME,
  reason TEXT,
  workplace TEXT,
  notes TEXT,
  confirmed_by_employee BOOLEAN,
  signature_path TEXT,
  signed_at TIMESTAMPTZ,
  client_timestamp TIMESTAMPTZ,
  client_timestamp_label TEXT,
  client_timezone TEXT,
  client_timezone_offset_minutes INTEGER,
  client_latitude DOUBLE PRECISION,
  client_longitude DOUBLE PRECISION,
  client_ip TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  review_note TEXT
);

ALTER TABLE times_entries
  ADD COLUMN IF NOT EXISTS location_address TEXT;

ALTER TABLE missed_punch_requests
  ADD COLUMN IF NOT EXISTS employee_name TEXT,
  ADD COLUMN IF NOT EXISTS forgotten_date DATE,
  ADD COLUMN IF NOT EXISTS entry_time TIME,
  ADD COLUMN IF NOT EXISTS exit_time TIME,
  ADD COLUMN IF NOT EXISTS reason TEXT,
  ADD COLUMN IF NOT EXISTS workplace TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS confirmed_by_employee BOOLEAN,
  ADD COLUMN IF NOT EXISTS signature_path TEXT,
  ADD COLUMN IF NOT EXISTS signed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS client_timestamp TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS client_timestamp_label TEXT,
  ADD COLUMN IF NOT EXISTS client_timezone TEXT,
  ADD COLUMN IF NOT EXISTS client_timezone_offset_minutes INTEGER,
  ADD COLUMN IF NOT EXISTS client_latitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS client_longitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS client_ip TEXT,
  ADD COLUMN IF NOT EXISTS requested_type TEXT,
  ADD COLUMN IF NOT EXISTS requested_occurred_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS note TEXT,
  ADD COLUMN IF NOT EXISTS signature_data_url TEXT;

CREATE INDEX IF NOT EXISTS idx_times_entries_user_id ON times_entries (user_id);
CREATE INDEX IF NOT EXISTS idx_times_entries_occurred_at ON times_entries (occurred_at);
CREATE INDEX IF NOT EXISTS idx_times_entries_so ON times_entries (service_order_id);

CREATE INDEX IF NOT EXISTS idx_alerts_user_id ON alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_resolved_at ON alerts(resolved_at);
CREATE INDEX IF NOT EXISTS idx_missed_punch_requests_user_id ON missed_punch_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_missed_punch_requests_created_at ON missed_punch_requests(created_at);
CREATE INDEX IF NOT EXISTS idx_missed_punch_requests_status ON missed_punch_requests(status);

CREATE INDEX IF NOT EXISTS idx_so_status ON service_orders(status);
CREATE INDEX IF NOT EXISTS idx_so_location_id ON service_orders(location_id);
CREATE INDEX IF NOT EXISTS idx_so_occurrence_type_id ON service_orders(occurrence_type_id);
CREATE INDEX IF NOT EXISTS idx_so_replaced_user_id ON service_orders(replaced_user_id);
CREATE INDEX IF NOT EXISTS idx_so_cover_user_id ON service_orders(cover_user_id);
CREATE INDEX IF NOT EXISTS idx_so_assign_user ON service_order_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_so_locations_name ON service_order_locations(name);
CREATE INDEX IF NOT EXISTS idx_occurrence_types_name ON occurrence_types(name);

CREATE UNIQUE INDEX IF NOT EXISTS idx_alerts_open_unique
ON alerts(type, user_id, time_in_entry_id)
WHERE resolved_at IS NULL;
